config/routes.rb
Applestoo::Application.routes.draw do
  devise_for :players, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'signup'}

  root 'home#index'

  get '/join' => 'players#show'
  post '/join' => 'players#show'
  resources :rounds

  get '/chooser/:secret_id', to: 'games#chooser', as: :chooser
  post '/chooser/:secret_id', to: 'games#chooser'

  get '/player/:secret_id', to: 'games#game_player', as: :player
  post '/player/:secret_id', to: 'games#game_player'

  if Rails.env.production?
   get '404', :to => 'home#index'
  end

end

app/models/round.rb
class Round < ActiveRecord::Base
  belongs_to :game
  belongs_to :player
  # has_one :green_card
  # has_many :turns
  has_many :red_cards
  # belongs_to :chooser, :class_name => "Player", :foreign_key => "chooser"
  # belongs_to :winner, :class_name => "Player", :foreign_key => "winner"
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  before_action :set_round, only: [:show, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token

  # GET /rounds
  # GET /rounds.json
  def index
    @rounds = Round.all
  end

  # GET /rounds/1
  # GET /rounds/1.json
  def show
    # @round = Round.where
  end

  # GET /rounds/new
  def new
    @round = Round.new
  end

  # GET /rounds/1/edit
  def edit
  end

  # POST /rounds
  # POST /rounds.json
  def create
    @round = Round.new(round_params)
    @player = current_player
    @round.game_id = @player.game_id

    respond_to do |format|
      if @round.save
        format.html { redirect_to @round, notice: 'Round was successfully created.' }
        format.json { render action: 'show', status: :created, location: @round }
      else
        format.html { render action: 'new' }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rounds/1
  # PATCH/PUT /rounds/1.json
  def update
    respond_to do |format|
      if @round.update(round_params)
        format.html { redirect_to @round, notice: 'Round was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rounds/1
  # DELETE /rounds/1.json
  def destroy
    @round.destroy
    respond_to do |format|
      format.html { redirect_to rounds_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_round
      @round = Round.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def round_params
      params.permit(:id, :game_id, :player_id, :red_card_id)
    end
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/views/rounds/index.html.erb
<h1>Listing rounds</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @rounds.each do |round| %>
      <tr>
        <td><%= link_to 'Show', round %></td>
        <td><%= link_to 'Edit', edit_round_path(round) %></td>
        <td><%= link_to 'Destroy', round, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Round', new_round_path %>

app/views/rounds/new.html.erb
<h1>New round</h1>

<%= render 'form' %>

<%= link_to 'Back', rounds_path %>

app/views/rounds/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_round_path(@round) %> |
<%= link_to 'Back', rounds_path %>