config/routes.rb
Applestoo::Application.routes.draw do
  devise_for :players, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'signup'}

  root 'home#index'

  get '/join' => 'players#show'
  post '/join' => 'players#show'
  resources :rounds

  get '/chooser/:secret_id', to: 'games#chooser', as: :chooser
  post '/chooser/:secret_id', to: 'games#chooser'

  get '/player/:secret_id', to: 'games#game_player', as: :player
  post '/player/:secret_id', to: 'games#game_player'

  if Rails.env.production?
   get '404', :to => 'home#index'
  end

end

app/models/player.rb
class Player < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :games
  has_many :turns
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def show
    @player = current_player
    # new_game = false
    if @player
      @game = Game.create
      game_id = @game.id
      @player[:game_id] = game_id
      @player.save
    end




    # if @player.save
    #   # link_to player_
    #   # redirect_to :controller => 'games', :action => 'chooser'
    #   # render :json => {:new_game_id => @game.secret_id}

    # end
  end



  # def join
  #   @player = Player.new(players_params)
  #   new_game = true
  #   if @player.plays.has_key?(:game_id)
  #     @game = Game.where("secret_id = '#{secret_id}").first
  # end

  private
  def players_params
    params.permit(:name, :game_id, :id, :secret_id)
  end


end

app/helpers/players_helper.rb
module PlayersHelper

end

app/views/players/chooser.html.erb
<!--


<nav id="nav">
  <ul>
    <li><a href="">ApplesToo</a></li>
  </ul>
</nav>
<div id="chooser_body">
  <div id="choose_card">Choose Green Card</div>
  <div id="round_card_reveal">
    <div id="green_card">
      <h3><%= get_random_green.adjective %></h3>
      <p><%= get_random_green.description %></p>
    </div>
  </div>
</div>
 -->

app/views/players/show.html.erb
<nav id="nav">
  <ul>
    <li><a href="">ApplesToo</a></li>
  </ul>
</nav>
<div id="chooser_body">
  <div class="flash">Which are you?</div>
  <!-- <a class="option" id="option" href="">Player</a> -->
  <!-- <a class="option" id="option" href="">Chooser</a> -->
  <%= link_to "Chooser", chooser_path(@game.secret_id), :class => "option", :id => "option" %>
  <%= link_to "Player", player_path(@game.secret_id), :class => "option" %>

  <!-- link_to new_gam -->

  <!-- <a class="option" href=<%= %> >Player</a>
  <a class="option" href="" >Chooser</a> -->
  <!-- <a class="option" href="">Player</a>
  <a class="option" href="">Chooser</a> -->
</div>